### PR TITLE
Added default topic prefix to reference.conf

### PR DESCRIPTION
**Pull request by WadeWaldron**

### CODE REVIEW

**Comment by jonas** [comment]
How is this different from the one in the `mesos.conf`? https://github.com/ypg-data/eigenflow/blob/eec213571aeea5ca2e289e675318644a93c8aefd/src/main/resources/mesos.conf#L41

**Comment by jonas** [comment]
Otherwise looks trivially good to me. :+1:

**Comment by WadeWaldron** [comment]
@jonas It isn't different from the one in mesos.conf.

mesos.conf is not used by default, only reference.conf is.  So we need it in reference.conf for it to actually take effect as a default.

**Comment by suhailshergill** [comment]
we should call it default.conf (bikeshedding time!)

On Wed, Mar 2, 2016 at 4:40 PM, Wade Waldron notifications@github.com
wrote:

> Merged #28 https://github.com/ypg-data/eigenflow/pull/28.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ypg-data/eigenflow/pull/28#event-575347593.

## 

Suhail

**Pull request merged**
